* Required
** Lua
*** Ubuntu
    #+begin_src sh :tangle yes
    sudo apt-get install lua5.1
    sudo apt-get install luarocks
    #+end_src
*** OSX
    #+begin_src sh :tangle yes
   $ brew install lua@5.1
    #+end_src

    https://github.com/Homebrew/homebrew-core/blob/aab30c37787da69f25f598be49cad19b2c90cf95/Formula/lua%405.1.rb

    #+begin_src sh :tangle yes
   # There's no way to link with homebrew so symlink it into a local bin directory.
   # It goes without saying, but ~/.bin will have to be in your path.
   $ ln -s /usr/local/bin/luarocks-5.1  ~/.bin/luarocks
   $ ln -s /usr/local/bin/lua-5.1 ~/.bin/lua
   $ ln -s /usr/local/bin/luac-5.1  ~/.bin/luac
   $ ln -s /usr/local/bin/luarocks-admin-5.1 ~/.bin/luarocks-admin
    #+end_src
** Love
*** Ubuntu
    #+begin_src sh :tangle yes
    $ sudo apt-get install love
    #+end_src
** Websockets
   [[file:src/vendor/websockets/README.org::*Doc][Websockets]]
** Json Library
   #+begin_src sh :tangle yes
   $ luarocks install lua-cjson
   #+end_src
** Lovetoys
   Lovetoys module path is wrong right now.
   #+begin_src sh :tangle yes
   luarocks install lovetoys
   #+end_src
* Building and Running
** Install Love2D SDK
   Download SDK from Love2D (https://love2d.org/) and follow instructions for your development machine. 
** Command `love`
   Check whether `love` is available on your command-line.
   > DEFINITION: `which N` return the path to command `N`.
     # Return path to Love
     $ which love
** Download
   Clone the repository folder
   $ git clone git@gitlab.com:parrottdrive/flappyworld.git
** Build for Desktop
   `pdrun` builds and runs our project in one step, launching the application in a window.
   $ cd flappyworld
   $ pdrun
** Build for iOS
   Get iOS source code from love2d.org. (https://bitbucket.org/rude/love/downloads/love-0.10.2-ios-source.zip)
   Open platform/xcode/love.xcodeproj with Xcode.
   Select love-ios target (not love-macosx)
   Select Build Phases of the 'love-ios' target and add your 'game.love' file into Copy Bundle Resources.
   Build the project.
   Your game should appear on your iOS device as an app.
   If you can't find the relevant XCode UI elements, you can refer to video tutorial on YouTube.
* Misc
** Style
   https://github.com/mpeterv/luacheck
   #+begin_src sh :tangle yes
   $ luarocks install luacheck
   #+end_src
* Testing
** Run all Tests
   Two ways:
   #+begin_src sh :tangle yes
   make test
   #+end_src

   #+begin_src sh :tangle yes
   lua test_suite.lua
   #+end_src
** Run one test
   #+begin_src sh :tangle yes
   lua test_file.lua
   #+end_src
** Run one test function
   #+begin_src sh :tangle yes
   lua test_file.lua test_function

   # Example
   lua phx_socket_test.lua test_phx_socket.test_make_ref__returns_number
   #+end_src

